### ISSUE TITLE
Give notice if mail routing is proper

### ISSUE THREAD

**Issue by cPanelSSP** [cPanelTechs/SSE#10]
Should add somewhere high: Mail is routed properly!
If in localdomains, check mx then A rec then if the server owns that server and if so, Mail is routed properly. (similar logic for remote & not hosted)
If in remote domains and IP not owned by server: Mail is NOT routed properly!

root@host [~]# perl sse.pl --domain=freewebhostingoffer.com

[INFO] * The domain freewebhostingoffer.com is owned by freeweb.
[INFO] * freewebhostingoffer.com is in LOCALDOMAINS.
[INFO] * The domain freewebhostingoffer.com resolves to IP: 
	 \_ 64.79.108.208
[INFO] * freewebhostingoffer.com has the folloiwng SPF records:
	\_ freewebhostingoffer.com. 14399	IN	TXT	"v=spf1 +a +mx +ip4:64.79.108.208 ~all"
[INFO] * freewebhostingoffer.com has the following domain keys:
 	\_ default._domainkey.freewebhostingoffer.com. 14399 IN TXT "v=DKIM1\; k=rsa\; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCskn8pposqUujRkJXVpWntIxwAz6cArUOC3shgd7VpGuXb8kAN7PcBNf0kGlG4ySWTUveDOEkt43uZTxNn6T6tl+0G57FIK+HvYONNEEDavWHpPxEA2Eo82xzcVwlXmUveVw5bVMRnYaxmMSwfCNNXUicEY6nCB/cHzLw3YjMQcQIDAQAB\;"
root@host [~]# echo 'freewebhostingoffer.com >> /etc/remotedomains
> ^C
root@host [~]# echo 'freewebhostingoffer.com' >> /etc/remotedomains
root@host [~]# perl sse.pl --domain=freewebhostingoffer.com

[INFO] * The domain freewebhostingoffer.com is owned by freeweb.
[INFO] * freewebhostingoffer.com is in LOCALDOMAINS.
[INFO] * freewebhostingoffer.com is in REMOTEDOMAINS.
[INFO] * The domain freewebhostingoffer.com resolves to IP: 
	 \_ 64.79.108.208
[INFO] * freewebhostingoffer.com has the folloiwng SPF records:
	\_ freewebhostingoffer.com. 14399	IN	TXT	"v=spf1 +a +mx +ip4:64.79.108.208 ~all"
[INFO] * freewebhostingoffer.com has the following domain keys:
 	\_ default._domainkey.freewebhostingoffer.com. 14399 IN TXT "v=DKIM1\; k=rsa\; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCskn8pposqUujRkJXVpWntIxwAz6cArUOC3shgd7VpGuXb8kAN7PcBNf0kGlG4ySWTUveDOEkt43uZTxNn6T6tl+0G57FIK+HvYONNEEDavWHpPxEA2Eo82xzcVwlXmUveVw5bVMRnYaxmMSwfCNNXUicEY6nCB/cHzLw3YjMQcQIDAQAB\;"
root@host [~]# dig mx +short freewebhostingoffer.com
0 freewebhostingoffer.com.
root@host [~]# dig a +short freewebhostingoffer.com
64.79.108.208
root@host [~]# ifconfig|grep 64.79.108.208
          inet addr:64.79.108.208  Bcast:64.79.108.255  Mask:255.255.255.128

**Comment by chrisice** [comment]
I think that the 7a179100b1f0c32503b11de484f28b8d953b58d6 commit took care of this.  If I'm wrong, just let me know!
