### ISSUE TITLE
Remote/Local domain check should report if a problem is detected

### ISSUE THREAD

**Issue by cborsheim** [cPanelTechs/SSE#4]
[INFO] * The domain freewebhostingoffer.com is owned by freeweb.
[INFO] * freewebhostingoffer.com is in REMOTEDOMAINS.
[INFO] * The domain freewebhostingoffer.com resolves to IP: 
	 \_ 64.79.108.208
root@host [~]# grep freewebhostingoffer.com /etc/*domains
/etc/localdomains:host.freewebhostingoffer.com
/etc/localdomains:ns1.freewebhostingoffer.com
/etc/localdomains:ns2.freewebhostingoffer.com
/etc/remotedomains:freewebhostingoffer.com
/etc/trueuserdomains:freewebhostingoffer.com: freeweb
/etc/userdatadomains:freewebhostingoffer.com: freeweb==root==main==freewebhostingoffer.com==/home/freeweb/public_html==64.79.108.208:80======0
/etc/userdomains:freewebhostingoffer.com: freeweb
root@host [~]# dig mx +short freewebhostingoffer.com
0 freewebhostingoffer.com.
root@host [~]# dig a +short freewebhostingoffer.com
64.79.108.208
root@host [~]# ifconfig|grep 64.79.108.208
          inet addr:64.79.108.208  Bcast:64.79.108.255  Mask:255.255.255.128

**Comment by chrisice** [comment]
This should be good in commit 38ef034

**Comment by chrisice** [comment]
commit 7a179100b1f0c32503b11de484f28b8d953b58d6 rather
