### ISSUE TITLE
--email broken.

### ISSUE THREAD

**Issue by baphometadata** [cPanelTechs/SSE#9]
root@hw1-x86 [~]# perl <(curl -s https://raw.githubusercontent.com/cPanelTechs/SSE/master/sse.pl) --email test@test.com
[WARN] * No Document root found
[WARN] * No Document root found
Use of uninitialized value $doc_root in pattern match (m//) at /dev/fd/63 line 617, <FILE> line 271.
[WARN] * No Document root found
Use of uninitialized value $doc_root in pattern match (m//) at /dev/fd/63 line 655, <FILE> line 271.
Use of uninitialized value $home in concatenation (.) or string at /dev/fd/63 line 663, <FILE> line 271.
readline() on closed filehandle FILE at /dev/fd/63 line 667, <FILE> line 271.

Happening on several different environments.

**Comment by chrisice** [comment]
This error is only with email accounts that don't exist.  Seems more like an error handling thing than a doesn't work thing

**Comment by chrisice** [comment]
definitely needs to be rewritten a little though

**Comment by batsyphus** [comment]
Noted -- was just about to test for that because I noticed the non-existent status on the for reals server.
